export interface Country {
  name: string;
  code: string; // 3-letter ISO 3166-1 alpha-3 code
  flag: string; // Emoji flag
}

export const countryList: Country[] = [
  { name: "Afghanistan", code: "AFG", flag: "🇦🇫" },
  { name: "Albania", code: "ALB", flag: "🇦🇱" },
  { name: "Algeria", code: "DZA", flag: "🇩🇿" },
  { name: "Andorra", code: "AND", flag: "🇦🇩" },
  { name: "Angola", code: "AGO", flag: "🇦🇴" },
  { name: "Argentina", code: "ARG", flag: "🇦🇷" },
  { name: "Armenia", code: "ARM", flag: "🇦🇲" },
  { name: "Australia", code: "AUS", flag: "🇦🇺" },
  { name: "Austria", code: "AUT", flag: "🇦🇹" },
  { name: "Azerbaijan", code: "AZE", flag: "🇦🇿" },
  { name: "Bahamas", code: "BHS", flag: "🇧🇸" },
  { name: "Bahrain", code: "BHR", flag: "🇧🇭" },
  { name: "Bangladesh", code: "BGD", flag: "🇧🇩" },
  { name: "Belarus", code: "BLR", flag: "🇧🇾" },
  { name: "Belgium", code: "BEL", flag: "🇧🇪" },
  { name: "Bhutan", code: "BTN", flag: "🇧🇹" },
  { name: "Bolivia", code: "BOL", flag: "🇧🇴" },
  { name: "Brazil", code: "BRA", flag: "🇧🇷" },
  { name: "Brunei", code: "BRN", flag: "🇧🇳" },
  { name: "Bulgaria", code: "BGR", flag: "🇧🇬" },
  { name: "Cambodia", code: "KHM", flag: "🇰🇭" },
  { name: "Cameroon", code: "CMR", flag: "🇨🇲" },
  { name: "Canada", code: "CAN", flag: "🇨🇦" },
  { name: "Chile", code: "CHL", flag: "🇨🇱" },
  { name: "China", code: "CHN", flag: "🇨🇳" },
  { name: "Colombia", code: "COL", flag: "🇨🇴" },
  { name: "Costa Rica", code: "CRI", flag: "🇨🇷" },
  { name: "Croatia", code: "HRV", flag: "🇭🇷" },
  { name: "Cuba", code: "CUB", flag: "🇨🇺" },
  { name: "Cyprus", code: "CYP", flag: "🇨🇾" },
  { name: "Czech Republic", code: "CZE", flag: "🇨🇿" },
  { name: "Denmark", code: "DNK", flag: "🇩🇰" },
  { name: "Ecuador", code: "ECU", flag: "🇪🇨" },
  { name: "Egypt", code: "EGY", flag: "🇪🇬" },
  { name: "Ethiopia", code: "ETH", flag: "🇪🇹" },
  { name: "Finland", code: "FIN", flag: "🇫🇮" },
  { name: "France", code: "FRA", flag: "🇫🇷" },
  { name: "Georgia", code: "GEO", flag: "🇬🇪" },
  { name: "Germany", code: "DEU", flag: "🇩🇪" },
  { name: "Ghana", code: "GHA", flag: "🇬🇭" },
  { name: "Greece", code: "GRC", flag: "🇬🇷" },
  { name: "Honduras", code: "HND", flag: "🇭🇳" },
  { name: "Hungary", code: "HUN", flag: "🇭🇺" },
  { name: "Iceland", code: "ISL", flag: "🇮🇸" },
  { name: "India", code: "IND", flag: "🇮🇳" },
  { name: "Indonesia", code: "IDN", flag: "🇮🇩" },
  { name: "Iran", code: "IRN", flag: "🇮🇷" },
  { name: "Iraq", code: "IRQ", flag: "🇮🇶" },
  { name: "Ireland", code: "IRL", flag: "🇮🇪" },
  { name: "Israel", code: "ISR", flag: "🇮🇱" },
  { name: "Italy", code: "ITA", flag: "🇮🇹" },
  { name: "Jamaica", code: "JAM", flag: "🇯🇲" },
  { name: "Japan", code: "JPN", flag: "🇯🇵" },
  { name: "Jordan", code: "JOR", flag: "🇯🇴" },
  { name: "Kazakhstan", code: "KAZ", flag: "🇰🇿" },
  { name: "Kenya", code: "KEN", flag: "🇰🇪" },
  { name: "Kuwait", code: "KWT", flag: "🇰🇼" },
  { name: "Kyrgyzstan", code: "KGZ", flag: "🇰🇬" },
  { name: "Laos", code: "LAO", flag: "🇱🇦" },
  { name: "Latvia", code: "LVA", flag: "🇱🇻" },
  { name: "Lebanon", code: "LBN", flag: "🇱🇧" },
  { name: "Liberia", code: "LBR", flag: "🇱🇷" },
  { name: "Libya", code: "LBY", flag: "🇱🇾" },
  { name: "Liechtenstein", code: "LIE", flag: "🇱🇮" },
  { name: "Lithuania", code: "LTU", flag: "🇱🇹" },
  { name: "Luxembourg", code: "LUX", flag: "🇱🇺" },
  { name: "Madagascar", code: "MDG", flag: "🇲🇬" },
  { name: "Malaysia", code: "MYS", flag: "🇲🇾" },
  { name: "Maldives", code: "MDV", flag: "🇲🇻" },
  { name: "Malta", code: "MLT", flag: "🇲🇹" },
  { name: "Mexico", code: "MEX", flag: "🇲🇽" },
  { name: "Monaco", code: "MCO", flag: "🇲🇨" },
  { name: "Mongolia", code: "MNG", flag: "🇲🇳" },
  { name: "Morocco", code: "MAR", flag: "🇲🇦" },
  { name: "Myanmar", code: "MMR", flag: "🇲🇲" },
  { name: "Nepal", code: "NPL", flag: "🇳🇵" },
  { name: "Netherlands", code: "NLD", flag: "🇳🇱" },
  { name: "New Zealand", code: "NZL", flag: "🇳🇿" },
  { name: "Nigeria", code: "NGA", flag: "🇳🇬" },
  { name: "North Korea", code: "PRK", flag: "🇰🇵" },
  { name: "Norway", code: "NOR", flag: "🇳🇴" },
  { name: "Oman", code: "OMN", flag: "🇴🇲" },
  { name: "Pakistan", code: "PAK", flag: "🇵🇰" },
  { name: "Panama", code: "PAN", flag: "🇵🇦" },
  { name: "Paraguay", code: "PRY", flag: "🇵🇾" },
  { name: "Peru", code: "PER", flag: "🇵🇪" },
  { name: "Philippines", code: "PHL", flag: "🇵🇭" },
  { name: "Poland", code: "POL", flag: "🇵🇱" },
  { name: "Portugal", code: "PRT", flag: "🇵🇹" },
  { name: "Qatar", code: "QAT", flag: "🇶🇦" },
  { name: "Romania", code: "ROU", flag: "🇷🇴" },
  { name: "Russia", code: "RUS", flag: "🇷🇺" },
  { name: "Saudi Arabia", code: "SAU", flag: "🇸🇦" },
  { name: "Singapore", code: "SGP", flag: "🇸🇬" },
  { name: "Slovakia", code: "SVK", flag: "🇸🇰" },
  { name: "South Africa", code: "ZAF", flag: "🇿🇦" },
  { name: "South Korea", code: "KOR", flag: "🇰🇷" },
  { name: "Spain", code: "ESP", flag: "🇪🇸" },
  { name: "Sri Lanka", code: "LKA", flag: "🇱🇰" },
  { name: "Sudan", code: "SDN", flag: "🇸🇩" },
  { name: "Sweden", code: "SWE", flag: "🇸🇪" },
  { name: "Switzerland", code: "CHE", flag: "🇨🇭" },
  { name: "Syria", code: "SYR", flag: "🇸🇾" },
  { name: "Taiwan", code: "TWN", flag: "🇹🇼" },
  { name: "Tajikistan", code: "TJK", flag: "🇹🇯" },
  { name: "Thailand", code: "THA", flag: "🇹🇭" },
  { name: "Turkey", code: "TUR", flag: "🇹🇷" },
  { name: "Ukraine", code: "UKR", flag: "🇺🇦" },
  { name: "United Arab Emirates", code: "ARE", flag: "🇦🇪" },
  { name: "United Kingdom", code: "GBR", flag: "🇬🇧" },
  { name: "United States", code: "USA", flag: "🇺🇸" },
  { name: "Uruguay", code: "URY", flag: "🇺🇾" },
  { name: "Uzbekistan", code: "UZB", flag: "🇺🇿" },
  { name: "Venezuela", code: "VEN", flag: "🇻🇪" },
  { name: "Vietnam", code: "VNM", flag: "🇻🇳" },
  { name: "Yemen", code: "YEM", flag: "🇾🇪" },
  { name: "Zimbabwe", code: "ZWE", flag: "🇿🇼" }
];
