import { Country } from "./types";

/**
 * Complete ISO 3166-1 static reference dataset (All 195 sovereign international nations)
 * Pure data structure safe for hydration in both Client Components and Server Components.
 */
export const ISO_MASTER_COUNTRIES: Country[] = [
  {
    "id": "c-afg",
    "name": "Afghanistan",
    "isoAlpha2": "AF",
    "isoAlpha3": "AFG",
    "isoNumeric": "004",
    "officialName": "Islamic Republic of Afghanistan",
    "nationality": "Afghan",
    "flag": "🇦🇫",
    "phoneCode": "+93",
    "region": "Asia",
    "subregion": "Southern Asia",
    "displayOrder": 1,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-alb",
    "name": "Albania",
    "isoAlpha2": "AL",
    "isoAlpha3": "ALB",
    "isoNumeric": "008",
    "officialName": "Republic of Albania",
    "nationality": "Albanian",
    "flag": "🇦🇱",
    "phoneCode": "+355",
    "region": "Europe",
    "subregion": "Southern Europe",
    "displayOrder": 2,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-dza",
    "name": "Algeria",
    "isoAlpha2": "DZ",
    "isoAlpha3": "DZA",
    "isoNumeric": "012",
    "officialName": "People's Democratic Republic of Algeria",
    "nationality": "Algerian",
    "flag": "🇩🇿",
    "phoneCode": "+213",
    "region": "Africa",
    "subregion": "Northern Africa",
    "displayOrder": 3,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-and",
    "name": "Andorra",
    "isoAlpha2": "AD",
    "isoAlpha3": "AND",
    "isoNumeric": "020",
    "officialName": "Principality of Andorra",
    "nationality": "Andorran",
    "flag": "🇦🇩",
    "phoneCode": "+376",
    "region": "Europe",
    "subregion": "Southern Europe",
    "displayOrder": 4,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-ago",
    "name": "Angola",
    "isoAlpha2": "AO",
    "isoAlpha3": "AGO",
    "isoNumeric": "024",
    "officialName": "Republic of Angola",
    "nationality": "Angolan",
    "flag": "🇦🇴",
    "phoneCode": "+244",
    "region": "Africa",
    "subregion": "Middle Africa",
    "displayOrder": 5,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-atg",
    "name": "Antigua and Barbuda",
    "isoAlpha2": "AG",
    "isoAlpha3": "ATG",
    "isoNumeric": "028",
    "officialName": "Antigua and Barbuda",
    "nationality": "Antiguan, Barbudan",
    "flag": "🇦🇬",
    "phoneCode": "+1-268",
    "region": "Americas",
    "subregion": "Caribbean",
    "displayOrder": 6,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-arg",
    "name": "Argentina",
    "isoAlpha2": "AR",
    "isoAlpha3": "ARG",
    "isoNumeric": "032",
    "officialName": "Argentine Republic",
    "nationality": "Argentine",
    "flag": "🇦🇷",
    "phoneCode": "+54",
    "region": "Americas",
    "subregion": "South America",
    "displayOrder": 7,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-arm",
    "name": "Armenia",
    "isoAlpha2": "AM",
    "isoAlpha3": "ARM",
    "isoNumeric": "051",
    "officialName": "Republic of Armenia",
    "nationality": "Armenian",
    "flag": "🇦🇲",
    "phoneCode": "+374",
    "region": "Asia",
    "subregion": "Western Asia",
    "displayOrder": 8,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-aus",
    "name": "Australia",
    "isoAlpha2": "AU",
    "isoAlpha3": "AUS",
    "isoNumeric": "036",
    "officialName": "Commonwealth of Australia",
    "nationality": "Australian",
    "flag": "🇦🇺",
    "phoneCode": "+61",
    "region": "Oceania",
    "subregion": "Australia and New Zealand",
    "displayOrder": 9,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-aut",
    "name": "Austria",
    "isoAlpha2": "AT",
    "isoAlpha3": "AUT",
    "isoNumeric": "040",
    "officialName": "Republic of Austria",
    "nationality": "Austrian",
    "flag": "🇦🇹",
    "phoneCode": "+43",
    "region": "Europe",
    "subregion": "Western Europe",
    "displayOrder": 10,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-aze",
    "name": "Azerbaijan",
    "isoAlpha2": "AZ",
    "isoAlpha3": "AZE",
    "isoNumeric": "031",
    "officialName": "Republic of Azerbaijan",
    "nationality": "Azerbaijani",
    "flag": "🇦🇿",
    "phoneCode": "+994",
    "region": "Asia",
    "subregion": "Western Asia",
    "displayOrder": 11,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-bhs",
    "name": "Bahamas",
    "isoAlpha2": "BS",
    "isoAlpha3": "BHS",
    "isoNumeric": "044",
    "officialName": "Commonwealth of the Bahamas",
    "nationality": "Bahamian",
    "flag": "🇧🇸",
    "phoneCode": "+1-242",
    "region": "Americas",
    "subregion": "Caribbean",
    "displayOrder": 12,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-bhr",
    "name": "Bahrain",
    "isoAlpha2": "BH",
    "isoAlpha3": "BHR",
    "isoNumeric": "048",
    "officialName": "Kingdom of Bahrain",
    "nationality": "Bahraini",
    "flag": "🇧🇭",
    "phoneCode": "+973",
    "region": "Asia",
    "subregion": "Western Asia",
    "displayOrder": 13,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-bgd",
    "name": "Bangladesh",
    "isoAlpha2": "BD",
    "isoAlpha3": "BGD",
    "isoNumeric": "050",
    "officialName": "People's Republic of Bangladesh",
    "nationality": "Bangladeshi",
    "flag": "🇧🇩",
    "phoneCode": "+880",
    "region": "Asia",
    "subregion": "Southern Asia",
    "displayOrder": 14,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-brb",
    "name": "Barbados",
    "isoAlpha2": "BB",
    "isoAlpha3": "BRB",
    "isoNumeric": "052",
    "officialName": "Barbados",
    "nationality": "Barbadian",
    "flag": "🇧🇧",
    "phoneCode": "+1-246",
    "region": "Americas",
    "subregion": "Caribbean",
    "displayOrder": 15,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-blr",
    "name": "Belarus",
    "isoAlpha2": "BY",
    "isoAlpha3": "BLR",
    "isoNumeric": "112",
    "officialName": "Republic of Belarus",
    "nationality": "Belarusian",
    "flag": "🇧🇾",
    "phoneCode": "+375",
    "region": "Europe",
    "subregion": "Eastern Europe",
    "displayOrder": 16,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-bel",
    "name": "Belgium",
    "isoAlpha2": "BE",
    "isoAlpha3": "BEL",
    "isoNumeric": "056",
    "officialName": "Kingdom of Belgium",
    "nationality": "Belgian",
    "flag": "🇧🇪",
    "phoneCode": "+32",
    "region": "Europe",
    "subregion": "Western Europe",
    "displayOrder": 17,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-blz",
    "name": "Belize",
    "isoAlpha2": "BZ",
    "isoAlpha3": "BLZ",
    "isoNumeric": "084",
    "officialName": "Belize",
    "nationality": "Belizean",
    "flag": "🇧🇿",
    "phoneCode": "+501",
    "region": "Americas",
    "subregion": "Central America",
    "displayOrder": 18,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-ben",
    "name": "Benin",
    "isoAlpha2": "BJ",
    "isoAlpha3": "BEN",
    "isoNumeric": "204",
    "officialName": "Republic of Benin",
    "nationality": "Beninese",
    "flag": "🇧🇯",
    "phoneCode": "+229",
    "region": "Africa",
    "subregion": "Western Africa",
    "displayOrder": 19,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-btn",
    "name": "Bhutan",
    "isoAlpha2": "BT",
    "isoAlpha3": "BTN",
    "isoNumeric": "064",
    "officialName": "Kingdom of Bhutan",
    "nationality": "Bhutanese",
    "flag": "🇧🇹",
    "phoneCode": "+975",
    "region": "Asia",
    "subregion": "Southern Asia",
    "displayOrder": 20,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-bol",
    "name": "Bolivia",
    "isoAlpha2": "BO",
    "isoAlpha3": "BOL",
    "isoNumeric": "068",
    "officialName": "Plurinational State of Bolivia",
    "nationality": "Bolivian",
    "flag": "🇧🇴",
    "phoneCode": "+591",
    "region": "Americas",
    "subregion": "South America",
    "displayOrder": 21,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-bih",
    "name": "Bosnia and Herzegovina",
    "isoAlpha2": "BA",
    "isoAlpha3": "BIH",
    "isoNumeric": "070",
    "officialName": "Bosnia and Herzegovina",
    "nationality": "Bosnian, Herzegovinian",
    "flag": "🇧🇦",
    "phoneCode": "+387",
    "region": "Europe",
    "subregion": "Southern Europe",
    "displayOrder": 22,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-bwa",
    "name": "Botswana",
    "isoAlpha2": "BW",
    "isoAlpha3": "BWA",
    "isoNumeric": "072",
    "officialName": "Republic of Botswana",
    "nationality": "Motswana",
    "flag": "🇧🇼",
    "phoneCode": "+267",
    "region": "Africa",
    "subregion": "Southern Africa",
    "displayOrder": 23,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-bra",
    "name": "Brazil",
    "isoAlpha2": "BR",
    "isoAlpha3": "BRA",
    "isoNumeric": "076",
    "officialName": "Federative Republic of Brazil",
    "nationality": "Brazilian",
    "flag": "🇧🇷",
    "phoneCode": "+55",
    "region": "Americas",
    "subregion": "South America",
    "displayOrder": 24,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-brn",
    "name": "Brunei",
    "isoAlpha2": "BN",
    "isoAlpha3": "BRN",
    "isoNumeric": "096",
    "officialName": "Brunei Darussalam",
    "nationality": "Bruneian",
    "flag": "🇧🇳",
    "phoneCode": "+673",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "displayOrder": 25,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-bgr",
    "name": "Bulgaria",
    "isoAlpha2": "BG",
    "isoAlpha3": "BGR",
    "isoNumeric": "100",
    "officialName": "Republic of Bulgaria",
    "nationality": "Bulgarian",
    "flag": "🇧🇬",
    "phoneCode": "+359",
    "region": "Europe",
    "subregion": "Eastern Europe",
    "displayOrder": 26,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-bfa",
    "name": "Burkina Faso",
    "isoAlpha2": "BF",
    "isoAlpha3": "BFA",
    "isoNumeric": "854",
    "officialName": "Burkina Faso",
    "nationality": "Burkinabé",
    "flag": "🇧🇫",
    "phoneCode": "+226",
    "region": "Africa",
    "subregion": "Western Africa",
    "displayOrder": 27,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-bdi",
    "name": "Burundi",
    "isoAlpha2": "BI",
    "isoAlpha3": "BDI",
    "isoNumeric": "108",
    "officialName": "Republic of Burundi",
    "nationality": "Burundian",
    "flag": "🇧🇮",
    "phoneCode": "+257",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "displayOrder": 28,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-cpv",
    "name": "Cabo Verde",
    "isoAlpha2": "CV",
    "isoAlpha3": "CPV",
    "isoNumeric": "132",
    "officialName": "Republic of Cabo Verde",
    "nationality": "Cabo Verdean",
    "flag": "🇨🇻",
    "phoneCode": "+238",
    "region": "Africa",
    "subregion": "Western Africa",
    "displayOrder": 29,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-khm",
    "name": "Cambodia",
    "isoAlpha2": "KH",
    "isoAlpha3": "KHM",
    "isoNumeric": "116",
    "officialName": "Kingdom of Cambodia",
    "nationality": "Cambodian",
    "flag": "🇰🇭",
    "phoneCode": "+855",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "displayOrder": 30,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-cmr",
    "name": "Cameroon",
    "isoAlpha2": "CM",
    "isoAlpha3": "CMR",
    "isoNumeric": "120",
    "officialName": "Republic of Cameroon",
    "nationality": "Cameroonian",
    "flag": "🇨🇲",
    "phoneCode": "+237",
    "region": "Africa",
    "subregion": "Middle Africa",
    "displayOrder": 31,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-can",
    "name": "Canada",
    "isoAlpha2": "CA",
    "isoAlpha3": "CAN",
    "isoNumeric": "124",
    "officialName": "Canada",
    "nationality": "Canadian",
    "flag": "🇨🇦",
    "phoneCode": "+1",
    "region": "Americas",
    "subregion": "Northern America",
    "displayOrder": 32,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-caf",
    "name": "Central African Republic",
    "isoAlpha2": "CF",
    "isoAlpha3": "CAF",
    "isoNumeric": "140",
    "officialName": "Central African Republic",
    "nationality": "Central African",
    "flag": "🇨🇫",
    "phoneCode": "+236",
    "region": "Africa",
    "subregion": "Middle Africa",
    "displayOrder": 33,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-tcd",
    "name": "Chad",
    "isoAlpha2": "TD",
    "isoAlpha3": "TCD",
    "isoNumeric": "148",
    "officialName": "Republic of Chad",
    "nationality": "Chadian",
    "flag": "🇹🇩",
    "phoneCode": "+235",
    "region": "Africa",
    "subregion": "Middle Africa",
    "displayOrder": 34,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-chl",
    "name": "Chile",
    "isoAlpha2": "CL",
    "isoAlpha3": "CHL",
    "isoNumeric": "152",
    "officialName": "Republic of Chile",
    "nationality": "Chilean",
    "flag": "🇨🇱",
    "phoneCode": "+56",
    "region": "Americas",
    "subregion": "South America",
    "displayOrder": 35,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-chn",
    "name": "China",
    "isoAlpha2": "CN",
    "isoAlpha3": "CHN",
    "isoNumeric": "156",
    "officialName": "People's Republic of China",
    "nationality": "Chinese",
    "flag": "🇨🇳",
    "phoneCode": "+86",
    "region": "Asia",
    "subregion": "Eastern Asia",
    "displayOrder": 36,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-col",
    "name": "Colombia",
    "isoAlpha2": "CO",
    "isoAlpha3": "COL",
    "isoNumeric": "170",
    "officialName": "Republic of Colombia",
    "nationality": "Colombian",
    "flag": "🇨🇴",
    "phoneCode": "+57",
    "region": "Americas",
    "subregion": "South America",
    "displayOrder": 37,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-com",
    "name": "Comoros",
    "isoAlpha2": "KM",
    "isoAlpha3": "COM",
    "isoNumeric": "174",
    "officialName": "Union of the Comoros",
    "nationality": "Comoran",
    "flag": "🇰🇲",
    "phoneCode": "+269",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "displayOrder": 38,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-cog",
    "name": "Congo (Congo-Brazzaville)",
    "isoAlpha2": "CG",
    "isoAlpha3": "COG",
    "isoNumeric": "178",
    "officialName": "Republic of the Congo",
    "nationality": "Congolese",
    "flag": "🇨🇬",
    "phoneCode": "+242",
    "region": "Africa",
    "subregion": "Middle Africa",
    "displayOrder": 39,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-cod",
    "name": "Congo (Democratic Republic)",
    "isoAlpha2": "CD",
    "isoAlpha3": "COD",
    "isoNumeric": "180",
    "officialName": "Democratic Republic of the Congo",
    "nationality": "Congolese",
    "flag": "🇨🇩",
    "phoneCode": "+243",
    "region": "Africa",
    "subregion": "Middle Africa",
    "displayOrder": 40,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-cri",
    "name": "Costa Rica",
    "isoAlpha2": "CR",
    "isoAlpha3": "CRI",
    "isoNumeric": "188",
    "officialName": "Republic of Costa Rica",
    "nationality": "Costa Rican",
    "flag": "🇨🇷",
    "phoneCode": "+506",
    "region": "Americas",
    "subregion": "Central America",
    "displayOrder": 41,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-hrv",
    "name": "Croatia",
    "isoAlpha2": "HR",
    "isoAlpha3": "HRV",
    "isoNumeric": "191",
    "officialName": "Republic of Croatia",
    "nationality": "Croatian",
    "flag": "🇭🇷",
    "phoneCode": "+385",
    "region": "Europe",
    "subregion": "Southern Europe",
    "displayOrder": 42,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-cub",
    "name": "Cuba",
    "isoAlpha2": "CU",
    "isoAlpha3": "CUB",
    "isoNumeric": "192",
    "officialName": "Republic of Cuba",
    "nationality": "Cuban",
    "flag": "🇨🇺",
    "phoneCode": "+53",
    "region": "Americas",
    "subregion": "Caribbean",
    "displayOrder": 43,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-cyp",
    "name": "Cyprus",
    "isoAlpha2": "CY",
    "isoAlpha3": "CYP",
    "isoNumeric": "196",
    "officialName": "Republic of Cyprus",
    "nationality": "Cypriot",
    "flag": "🇨🇾",
    "phoneCode": "+357",
    "region": "Europe",
    "subregion": "Southern Europe",
    "displayOrder": 44,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-cze",
    "name": "Czech Republic",
    "isoAlpha2": "CZ",
    "isoAlpha3": "CZE",
    "isoNumeric": "203",
    "officialName": "Czech Republic",
    "nationality": "Czech",
    "flag": "🇨🇿",
    "phoneCode": "+420",
    "region": "Europe",
    "subregion": "Eastern Europe",
    "displayOrder": 45,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-dnk",
    "name": "Denmark",
    "isoAlpha2": "DK",
    "isoAlpha3": "DNK",
    "isoNumeric": "208",
    "officialName": "Kingdom of Denmark",
    "nationality": "Danish",
    "flag": "🇩🇰",
    "phoneCode": "+45",
    "region": "Europe",
    "subregion": "Northern Europe",
    "displayOrder": 46,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-dji",
    "name": "Djibouti",
    "isoAlpha2": "DJ",
    "isoAlpha3": "DJI",
    "isoNumeric": "262",
    "officialName": "Republic of Djibouti",
    "nationality": "Djiboutian",
    "flag": "🇩🇯",
    "phoneCode": "+253",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "displayOrder": 47,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-dma",
    "name": "Dominica",
    "isoAlpha2": "DM",
    "isoAlpha3": "DMA",
    "isoNumeric": "212",
    "officialName": "Commonwealth of Dominica",
    "nationality": "Dominican",
    "flag": "🇩🇲",
    "phoneCode": "+1-767",
    "region": "Americas",
    "subregion": "Caribbean",
    "displayOrder": 48,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-dom",
    "name": "Dominican Republic",
    "isoAlpha2": "DO",
    "isoAlpha3": "DOM",
    "isoNumeric": "214",
    "officialName": "Dominican Republic",
    "nationality": "Dominican",
    "flag": "🇩🇴",
    "phoneCode": "+1-809",
    "region": "Americas",
    "subregion": "Caribbean",
    "displayOrder": 49,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-ecu",
    "name": "Ecuador",
    "isoAlpha2": "EC",
    "isoAlpha3": "ECU",
    "isoNumeric": "218",
    "officialName": "Republic of Ecuador",
    "nationality": "Ecuadorean",
    "flag": "🇪🇨",
    "phoneCode": "+593",
    "region": "Americas",
    "subregion": "South America",
    "displayOrder": 50,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-egy",
    "name": "Egypt",
    "isoAlpha2": "EG",
    "isoAlpha3": "EGY",
    "isoNumeric": "818",
    "officialName": "Arab Republic of Egypt",
    "nationality": "Egyptian",
    "flag": "🇪🇬",
    "phoneCode": "+20",
    "region": "Africa",
    "subregion": "Northern Africa",
    "displayOrder": 51,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-slv",
    "name": "El Salvador",
    "isoAlpha2": "SV",
    "isoAlpha3": "SLV",
    "isoNumeric": "222",
    "officialName": "Republic of El Salvador",
    "nationality": "Salvadoran",
    "flag": "🇸🇻",
    "phoneCode": "+503",
    "region": "Americas",
    "subregion": "Central America",
    "displayOrder": 52,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-gnq",
    "name": "Equatorial Guinea",
    "isoAlpha2": "GQ",
    "isoAlpha3": "GNQ",
    "isoNumeric": "226",
    "officialName": "Republic of Equatorial Guinea",
    "nationality": "Equatorial Guinean",
    "flag": "🇬🇶",
    "phoneCode": "+240",
    "region": "Africa",
    "subregion": "Middle Africa",
    "displayOrder": 53,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-eri",
    "name": "Eritrea",
    "isoAlpha2": "ER",
    "isoAlpha3": "ERI",
    "isoNumeric": "232",
    "officialName": "State of Eritrea",
    "nationality": "Eritrean",
    "flag": "🇪🇷",
    "phoneCode": "+291",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "displayOrder": 54,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-est",
    "name": "Estonia",
    "isoAlpha2": "EE",
    "isoAlpha3": "EST",
    "isoNumeric": "233",
    "officialName": "Republic of Estonia",
    "nationality": "Estonian",
    "flag": "🇪🇪",
    "phoneCode": "+372",
    "region": "Europe",
    "subregion": "Northern Europe",
    "displayOrder": 55,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-swz",
    "name": "Eswatini",
    "isoAlpha2": "SZ",
    "isoAlpha3": "SWZ",
    "isoNumeric": "748",
    "officialName": "Kingdom of Eswatini",
    "nationality": "Swazi",
    "flag": "🇸🇿",
    "phoneCode": "+268",
    "region": "Africa",
    "subregion": "Southern Africa",
    "displayOrder": 56,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-eth",
    "name": "Ethiopia",
    "isoAlpha2": "ET",
    "isoAlpha3": "ETH",
    "isoNumeric": "231",
    "officialName": "Federal Democratic Republic of Ethiopia",
    "nationality": "Ethiopian",
    "flag": "🇪🇹",
    "phoneCode": "+251",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "displayOrder": 57,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-fji",
    "name": "Fiji",
    "isoAlpha2": "FJ",
    "isoAlpha3": "FJI",
    "isoNumeric": "242",
    "officialName": "Republic of Fiji",
    "nationality": "Fijian",
    "flag": "🇫🇯",
    "phoneCode": "+679",
    "region": "Oceania",
    "subregion": "Melanesia",
    "displayOrder": 58,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-fin",
    "name": "Finland",
    "isoAlpha2": "FI",
    "isoAlpha3": "FIN",
    "isoNumeric": "246",
    "officialName": "Republic of Finland",
    "nationality": "Finnish",
    "flag": "🇫🇮",
    "phoneCode": "+358",
    "region": "Europe",
    "subregion": "Northern Europe",
    "displayOrder": 59,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-fra",
    "name": "France",
    "isoAlpha2": "FR",
    "isoAlpha3": "FRA",
    "isoNumeric": "250",
    "officialName": "French Republic",
    "nationality": "French",
    "flag": "🇫🇷",
    "phoneCode": "+33",
    "region": "Europe",
    "subregion": "Western Europe",
    "displayOrder": 60,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-gab",
    "name": "Gabon",
    "isoAlpha2": "GA",
    "isoAlpha3": "GAB",
    "isoNumeric": "266",
    "officialName": "Gabonese Republic",
    "nationality": "Gabonese",
    "flag": "🇬🇦",
    "phoneCode": "+241",
    "region": "Africa",
    "subregion": "Middle Africa",
    "displayOrder": 61,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-gmb",
    "name": "Gambia",
    "isoAlpha2": "GM",
    "isoAlpha3": "GMB",
    "isoNumeric": "270",
    "officialName": "Republic of the Gambia",
    "nationality": "Gambian",
    "flag": "🇬🇲",
    "phoneCode": "+220",
    "region": "Africa",
    "subregion": "Western Africa",
    "displayOrder": 62,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-geo",
    "name": "Georgia",
    "isoAlpha2": "GE",
    "isoAlpha3": "GEO",
    "isoNumeric": "268",
    "officialName": "Georgia",
    "nationality": "Georgian",
    "flag": "🇬🇪",
    "phoneCode": "+995",
    "region": "Asia",
    "subregion": "Western Asia",
    "displayOrder": 63,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-deu",
    "name": "Germany",
    "isoAlpha2": "DE",
    "isoAlpha3": "DEU",
    "isoNumeric": "276",
    "officialName": "Federal Republic of Germany",
    "nationality": "German",
    "flag": "🇩🇪",
    "phoneCode": "+49",
    "region": "Europe",
    "subregion": "Western Europe",
    "displayOrder": 64,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-gha",
    "name": "Ghana",
    "isoAlpha2": "GH",
    "isoAlpha3": "GHA",
    "isoNumeric": "288",
    "officialName": "Republic of Ghana",
    "nationality": "Ghanaian",
    "flag": "🇬🇭",
    "phoneCode": "+233",
    "region": "Africa",
    "subregion": "Western Africa",
    "displayOrder": 65,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-grc",
    "name": "Greece",
    "isoAlpha2": "GR",
    "isoAlpha3": "GRC",
    "isoNumeric": "300",
    "officialName": "Hellenic Republic",
    "nationality": "Greek",
    "flag": "🇬🇷",
    "phoneCode": "+30",
    "region": "Europe",
    "subregion": "Southern Europe",
    "displayOrder": 66,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-grd",
    "name": "Grenada",
    "isoAlpha2": "GD",
    "isoAlpha3": "GRD",
    "isoNumeric": "308",
    "officialName": "Grenada",
    "nationality": "Grenadian",
    "flag": "🇬🇩",
    "phoneCode": "+1-473",
    "region": "Americas",
    "subregion": "Caribbean",
    "displayOrder": 67,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-gtm",
    "name": "Guatemala",
    "isoAlpha2": "GT",
    "isoAlpha3": "GTM",
    "isoNumeric": "320",
    "officialName": "Republic of Guatemala",
    "nationality": "Guatemalan",
    "flag": "🇬🇹",
    "phoneCode": "+502",
    "region": "Americas",
    "subregion": "Central America",
    "displayOrder": 68,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-gin",
    "name": "Guinea",
    "isoAlpha2": "GN",
    "isoAlpha3": "GIN",
    "isoNumeric": "324",
    "officialName": "Republic of Guinea",
    "nationality": "Guinean",
    "flag": "🇬🇳",
    "phoneCode": "+224",
    "region": "Africa",
    "subregion": "Western Africa",
    "displayOrder": 69,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-gnb",
    "name": "Guinea-Bissau",
    "isoAlpha2": "GW",
    "isoAlpha3": "GNB",
    "isoNumeric": "624",
    "officialName": "Republic of Guinea-Bissau",
    "nationality": "Bissau-Guinean",
    "flag": "🇬🇼",
    "phoneCode": "+245",
    "region": "Africa",
    "subregion": "Western Africa",
    "displayOrder": 70,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-guy",
    "name": "Guyana",
    "isoAlpha2": "GY",
    "isoAlpha3": "GUY",
    "isoNumeric": "328",
    "officialName": "Co-operative Republic of Guyana",
    "nationality": "Guyanese",
    "flag": "🇬🇾",
    "phoneCode": "+592",
    "region": "Americas",
    "subregion": "South America",
    "displayOrder": 71,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-hti",
    "name": "Haiti",
    "isoAlpha2": "HT",
    "isoAlpha3": "HTI",
    "isoNumeric": "332",
    "officialName": "Republic of Haiti",
    "nationality": "Haitian",
    "flag": "🇭🇹",
    "phoneCode": "+509",
    "region": "Americas",
    "subregion": "Caribbean",
    "displayOrder": 72,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-hnd",
    "name": "Honduras",
    "isoAlpha2": "HN",
    "isoAlpha3": "HND",
    "isoNumeric": "340",
    "officialName": "Republic of Honduras",
    "nationality": "Honduran",
    "flag": "🇭🇳",
    "phoneCode": "+504",
    "region": "Americas",
    "subregion": "Central America",
    "displayOrder": 73,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-hun",
    "name": "Hungary",
    "isoAlpha2": "HU",
    "isoAlpha3": "HUN",
    "isoNumeric": "348",
    "officialName": "Hungary",
    "nationality": "Hungarian",
    "flag": "🇭🇺",
    "phoneCode": "+36",
    "region": "Europe",
    "subregion": "Eastern Europe",
    "displayOrder": 74,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-isl",
    "name": "Iceland",
    "isoAlpha2": "IS",
    "isoAlpha3": "ISL",
    "isoNumeric": "352",
    "officialName": "Republic of Iceland",
    "nationality": "Icelandic",
    "flag": "🇮🇸",
    "phoneCode": "+354",
    "region": "Europe",
    "subregion": "Northern Europe",
    "displayOrder": 75,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-ind",
    "name": "India",
    "isoAlpha2": "IN",
    "isoAlpha3": "IND",
    "isoNumeric": "356",
    "officialName": "Republic of India",
    "nationality": "Indian",
    "flag": "🇮🇳",
    "phoneCode": "+91",
    "region": "Asia",
    "subregion": "Southern Asia",
    "displayOrder": 76,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-idn",
    "name": "Indonesia",
    "isoAlpha2": "ID",
    "isoAlpha3": "IDN",
    "isoNumeric": "360",
    "officialName": "Republic of Indonesia",
    "nationality": "Indonesian",
    "flag": "🇮🇩",
    "phoneCode": "+62",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "displayOrder": 77,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-irn",
    "name": "Iran",
    "isoAlpha2": "IR",
    "isoAlpha3": "IRN",
    "isoNumeric": "364",
    "officialName": "Islamic Republic of Iran",
    "nationality": "Iranian",
    "flag": "🇮🇷",
    "phoneCode": "+98",
    "region": "Asia",
    "subregion": "Southern Asia",
    "displayOrder": 78,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-irq",
    "name": "Iraq",
    "isoAlpha2": "IQ",
    "isoAlpha3": "IRQ",
    "isoNumeric": "368",
    "officialName": "Republic of Iraq",
    "nationality": "Iraqi",
    "flag": "🇮🇶",
    "phoneCode": "+964",
    "region": "Asia",
    "subregion": "Western Asia",
    "displayOrder": 79,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-irl",
    "name": "Ireland",
    "isoAlpha2": "IE",
    "isoAlpha3": "IRL",
    "isoNumeric": "372",
    "officialName": "Ireland",
    "nationality": "Irish",
    "flag": "🇮🇪",
    "phoneCode": "+353",
    "region": "Europe",
    "subregion": "Northern Europe",
    "displayOrder": 80,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-isr",
    "name": "Israel",
    "isoAlpha2": "IL",
    "isoAlpha3": "ISR",
    "isoNumeric": "376",
    "officialName": "State of Israel",
    "nationality": "Israeli",
    "flag": "🇮🇱",
    "phoneCode": "+972",
    "region": "Asia",
    "subregion": "Western Asia",
    "displayOrder": 81,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-ita",
    "name": "Italy",
    "isoAlpha2": "IT",
    "isoAlpha3": "ITA",
    "isoNumeric": "380",
    "officialName": "Italian Republic",
    "nationality": "Italian",
    "flag": "🇮🇹",
    "phoneCode": "+39",
    "region": "Europe",
    "subregion": "Southern Europe",
    "displayOrder": 82,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-jam",
    "name": "Jamaica",
    "isoAlpha2": "JM",
    "isoAlpha3": "JAM",
    "isoNumeric": "388",
    "officialName": "Jamaica",
    "nationality": "Jamaican",
    "flag": "🇯🇲",
    "phoneCode": "+1-876",
    "region": "Americas",
    "subregion": "Caribbean",
    "displayOrder": 83,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-jpn",
    "name": "Japan",
    "isoAlpha2": "JP",
    "isoAlpha3": "JPN",
    "isoNumeric": "392",
    "officialName": "Japan",
    "nationality": "Japanese",
    "flag": "🇯🇵",
    "phoneCode": "+81",
    "region": "Asia",
    "subregion": "Eastern Asia",
    "displayOrder": 84,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-jor",
    "name": "Jordan",
    "isoAlpha2": "JO",
    "isoAlpha3": "JOR",
    "isoNumeric": "400",
    "officialName": "Hashemite Kingdom of Jordan",
    "nationality": "Jordanian",
    "flag": "🇯🇴",
    "phoneCode": "+962",
    "region": "Asia",
    "subregion": "Western Asia",
    "displayOrder": 85,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-kaz",
    "name": "Kazakhstan",
    "isoAlpha2": "KZ",
    "isoAlpha3": "KAZ",
    "isoNumeric": "398",
    "officialName": "Republic of Kazakhstan",
    "nationality": "Kazakhstani",
    "flag": "🇰🇿",
    "phoneCode": "+7",
    "region": "Asia",
    "subregion": "Central Asia",
    "displayOrder": 86,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-ken",
    "name": "Kenya",
    "isoAlpha2": "KE",
    "isoAlpha3": "KEN",
    "isoNumeric": "404",
    "officialName": "Republic of Kenya",
    "nationality": "Kenyan",
    "flag": "🇰🇪",
    "phoneCode": "+254",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "displayOrder": 87,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-kir",
    "name": "Kiribati",
    "isoAlpha2": "KI",
    "isoAlpha3": "KIR",
    "isoNumeric": "296",
    "officialName": "Republic of Kiribati",
    "nationality": "I-Kiribati",
    "flag": "🇰🇮",
    "phoneCode": "+686",
    "region": "Oceania",
    "subregion": "Micronesia",
    "displayOrder": 88,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-kwt",
    "name": "Kuwait",
    "isoAlpha2": "KW",
    "isoAlpha3": "KWT",
    "isoNumeric": "414",
    "officialName": "State of Kuwait",
    "nationality": "Kuwaiti",
    "flag": "🇰🇼",
    "phoneCode": "+965",
    "region": "Asia",
    "subregion": "Western Asia",
    "displayOrder": 89,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-kgz",
    "name": "Kyrgyzstan",
    "isoAlpha2": "KG",
    "isoAlpha3": "KGZ",
    "isoNumeric": "417",
    "officialName": "Kyrgyz Republic",
    "nationality": "Kyrgyzstani",
    "flag": "🇰🇬",
    "phoneCode": "+996",
    "region": "Asia",
    "subregion": "Central Asia",
    "displayOrder": 90,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-lao",
    "name": "Laos",
    "isoAlpha2": "LA",
    "isoAlpha3": "LAO",
    "isoNumeric": "418",
    "officialName": "Lao People's Democratic Republic",
    "nationality": "Laotian",
    "flag": "🇱🇦",
    "phoneCode": "+856",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "displayOrder": 91,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-lva",
    "name": "Latvia",
    "isoAlpha2": "LV",
    "isoAlpha3": "LVA",
    "isoNumeric": "428",
    "officialName": "Republic of Latvia",
    "nationality": "Latvian",
    "flag": "🇱🇻",
    "phoneCode": "+371",
    "region": "Europe",
    "subregion": "Northern Europe",
    "displayOrder": 92,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-lbn",
    "name": "Lebanon",
    "isoAlpha2": "LB",
    "isoAlpha3": "LBN",
    "isoNumeric": "422",
    "officialName": "Lebanese Republic",
    "nationality": "Lebanese",
    "flag": "🇱🇧",
    "phoneCode": "+961",
    "region": "Asia",
    "subregion": "Western Asia",
    "displayOrder": 93,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-lso",
    "name": "Lesotho",
    "isoAlpha2": "LS",
    "isoAlpha3": "LSO",
    "isoNumeric": "426",
    "officialName": "Kingdom of Lesotho",
    "nationality": "Basotho",
    "flag": "🇱🇸",
    "phoneCode": "+266",
    "region": "Africa",
    "subregion": "Southern Africa",
    "displayOrder": 94,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-lbr",
    "name": "Liberia",
    "isoAlpha2": "LR",
    "isoAlpha3": "LBR",
    "isoNumeric": "430",
    "officialName": "Republic of Liberia",
    "nationality": "Liberian",
    "flag": "🇱🇷",
    "phoneCode": "+231",
    "region": "Africa",
    "subregion": "Western Africa",
    "displayOrder": 95,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-lby",
    "name": "Libya",
    "isoAlpha2": "LY",
    "isoAlpha3": "LBY",
    "isoNumeric": "434",
    "officialName": "State of Libya",
    "nationality": "Libyan",
    "flag": "🇱🇾",
    "phoneCode": "+218",
    "region": "Africa",
    "subregion": "Northern Africa",
    "displayOrder": 96,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-lie",
    "name": "Liechtenstein",
    "isoAlpha2": "LI",
    "isoAlpha3": "LIE",
    "isoNumeric": "438",
    "officialName": "Principality of Liechtenstein",
    "nationality": "Liechtensteiner",
    "flag": "🇱🇮",
    "phoneCode": "+423",
    "region": "Europe",
    "subregion": "Western Europe",
    "displayOrder": 97,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-ltu",
    "name": "Lithuania",
    "isoAlpha2": "LT",
    "isoAlpha3": "LTU",
    "isoNumeric": "440",
    "officialName": "Republic of Lithuania",
    "nationality": "Lithuanian",
    "flag": "🇱🇹",
    "phoneCode": "+370",
    "region": "Europe",
    "subregion": "Northern Europe",
    "displayOrder": 98,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-lux",
    "name": "Luxembourg",
    "isoAlpha2": "LU",
    "isoAlpha3": "LUX",
    "isoNumeric": "442",
    "officialName": "Grand Duchy of Luxembourg",
    "nationality": "Luxembourger",
    "flag": "🇱🇺",
    "phoneCode": "+352",
    "region": "Europe",
    "subregion": "Western Europe",
    "displayOrder": 99,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-mdg",
    "name": "Madagascar",
    "isoAlpha2": "MG",
    "isoAlpha3": "MDG",
    "isoNumeric": "450",
    "officialName": "Republic of Madagascar",
    "nationality": "Malagasy",
    "flag": "🇲🇬",
    "phoneCode": "+261",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "displayOrder": 100,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-mwi",
    "name": "Malawi",
    "isoAlpha2": "MW",
    "isoAlpha3": "MWI",
    "isoNumeric": "454",
    "officialName": "Republic of Malawi",
    "nationality": "Malawian",
    "flag": "🇲🇼",
    "phoneCode": "+265",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "displayOrder": 101,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-mys",
    "name": "Malaysia",
    "isoAlpha2": "MY",
    "isoAlpha3": "MYS",
    "isoNumeric": "458",
    "officialName": "Malaysia",
    "nationality": "Malaysian",
    "flag": "🇲🇾",
    "phoneCode": "+60",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "displayOrder": 102,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-mdv",
    "name": "Maldives",
    "isoAlpha2": "MV",
    "isoAlpha3": "MDV",
    "isoNumeric": "462",
    "officialName": "Republic of Maldives",
    "nationality": "Maldivian",
    "flag": "🇲🇻",
    "phoneCode": "+960",
    "region": "Asia",
    "subregion": "Southern Asia",
    "displayOrder": 103,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-mli",
    "name": "Mali",
    "isoAlpha2": "ML",
    "isoAlpha3": "MLI",
    "isoNumeric": "466",
    "officialName": "Republic of Mali",
    "nationality": "Malian",
    "flag": "🇲🇱",
    "phoneCode": "+223",
    "region": "Africa",
    "subregion": "Western Africa",
    "displayOrder": 104,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-mlt",
    "name": "Malta",
    "isoAlpha2": "MT",
    "isoAlpha3": "MLT",
    "isoNumeric": "470",
    "officialName": "Republic of Malta",
    "nationality": "Maltese",
    "flag": "🇲🇹",
    "phoneCode": "+356",
    "region": "Europe",
    "subregion": "Southern Europe",
    "displayOrder": 105,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-mhl",
    "name": "Marshall Islands",
    "isoAlpha2": "MH",
    "isoAlpha3": "MHL",
    "isoNumeric": "584",
    "officialName": "Republic of the Marshall Islands",
    "nationality": "Marshallese",
    "flag": "🇲🇭",
    "phoneCode": "+692",
    "region": "Oceania",
    "subregion": "Micronesia",
    "displayOrder": 106,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-mrt",
    "name": "Mauritania",
    "isoAlpha2": "MR",
    "isoAlpha3": "MRT",
    "isoNumeric": "478",
    "officialName": "Islamic Republic of Mauritania",
    "nationality": "Mauritanian",
    "flag": "🇲🇷",
    "phoneCode": "+222",
    "region": "Africa",
    "subregion": "Western Africa",
    "displayOrder": 107,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-mus",
    "name": "Mauritius",
    "isoAlpha2": "MU",
    "isoAlpha3": "MUS",
    "isoNumeric": "480",
    "officialName": "Republic of Mauritius",
    "nationality": "Mauritian",
    "flag": "🇲🇺",
    "phoneCode": "+230",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "displayOrder": 108,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-mex",
    "name": "Mexico",
    "isoAlpha2": "MX",
    "isoAlpha3": "MEX",
    "isoNumeric": "484",
    "officialName": "United Mexican States",
    "nationality": "Mexican",
    "flag": "🇲🇽",
    "phoneCode": "+52",
    "region": "Americas",
    "subregion": "Central America",
    "displayOrder": 109,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-fsm",
    "name": "Micronesia",
    "isoAlpha2": "FM",
    "isoAlpha3": "FSM",
    "isoNumeric": "583",
    "officialName": "Federated States of Micronesia",
    "nationality": "Micronesian",
    "flag": "🇫🇲",
    "phoneCode": "+691",
    "region": "Oceania",
    "subregion": "Micronesia",
    "displayOrder": 110,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-mda",
    "name": "Moldova",
    "isoAlpha2": "MD",
    "isoAlpha3": "MDA",
    "isoNumeric": "498",
    "officialName": "Republic of Moldova",
    "nationality": "Moldovan",
    "flag": "🇲🇩",
    "phoneCode": "+373",
    "region": "Europe",
    "subregion": "Eastern Europe",
    "displayOrder": 111,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-mco",
    "name": "Monaco",
    "isoAlpha2": "MC",
    "isoAlpha3": "MCO",
    "isoNumeric": "492",
    "officialName": "Principality of Monaco",
    "nationality": "Monégasque",
    "flag": "🇲🇨",
    "phoneCode": "+377",
    "region": "Europe",
    "subregion": "Western Europe",
    "displayOrder": 112,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-mng",
    "name": "Mongolia",
    "isoAlpha2": "MN",
    "isoAlpha3": "MNG",
    "isoNumeric": "496",
    "officialName": "Mongolia",
    "nationality": "Mongolian",
    "flag": "🇲🇳",
    "phoneCode": "+976",
    "region": "Asia",
    "subregion": "Eastern Asia",
    "displayOrder": 113,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-mne",
    "name": "Montenegro",
    "isoAlpha2": "ME",
    "isoAlpha3": "MNE",
    "isoNumeric": "499",
    "officialName": "Montenegro",
    "nationality": "Montenegrin",
    "flag": "🇲🇪",
    "phoneCode": "+382",
    "region": "Europe",
    "subregion": "Southern Europe",
    "displayOrder": 114,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-mar",
    "name": "Morocco",
    "isoAlpha2": "MA",
    "isoAlpha3": "MAR",
    "isoNumeric": "504",
    "officialName": "Kingdom of Morocco",
    "nationality": "Moroccan",
    "flag": "🇲🇦",
    "phoneCode": "+212",
    "region": "Africa",
    "subregion": "Northern Africa",
    "displayOrder": 115,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-moz",
    "name": "Mozambique",
    "isoAlpha2": "MZ",
    "isoAlpha3": "MOZ",
    "isoNumeric": "508",
    "officialName": "Republic of Mozambique",
    "nationality": "Mozambican",
    "flag": "🇲🇿",
    "phoneCode": "+258",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "displayOrder": 116,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-mmr",
    "name": "Myanmar",
    "isoAlpha2": "MM",
    "isoAlpha3": "MMR",
    "isoNumeric": "104",
    "officialName": "Republic of the Union of Myanmar",
    "nationality": "Burmese",
    "flag": "🇲🇲",
    "phoneCode": "+95",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "displayOrder": 117,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-nam",
    "name": "Namibia",
    "isoAlpha2": "NA",
    "isoAlpha3": "NAM",
    "isoNumeric": "516",
    "officialName": "Republic of Namibia",
    "nationality": "Namibian",
    "flag": "🇳🇦",
    "phoneCode": "+264",
    "region": "Africa",
    "subregion": "Southern Africa",
    "displayOrder": 118,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-nru",
    "name": "Nauru",
    "isoAlpha2": "NR",
    "isoAlpha3": "NRU",
    "isoNumeric": "520",
    "officialName": "Republic of Nauru",
    "nationality": "Nauruan",
    "flag": "🇳🇷",
    "phoneCode": "+674",
    "region": "Oceania",
    "subregion": "Micronesia",
    "displayOrder": 119,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-npl",
    "name": "Nepal",
    "isoAlpha2": "NP",
    "isoAlpha3": "NPL",
    "isoNumeric": "524",
    "officialName": "Federal Democratic Republic of Nepal",
    "nationality": "Nepalese",
    "flag": "🇳🇵",
    "phoneCode": "+977",
    "region": "Asia",
    "subregion": "Southern Asia",
    "displayOrder": 120,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-nld",
    "name": "Netherlands",
    "isoAlpha2": "NL",
    "isoAlpha3": "NLD",
    "isoNumeric": "528",
    "officialName": "Kingdom of the Netherlands",
    "nationality": "Dutch",
    "flag": "🇳🇱",
    "phoneCode": "+31",
    "region": "Europe",
    "subregion": "Western Europe",
    "displayOrder": 121,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-nzl",
    "name": "New Zealand",
    "isoAlpha2": "NZ",
    "isoAlpha3": "NZL",
    "isoNumeric": "554",
    "officialName": "New Zealand",
    "nationality": "New Zealander",
    "flag": "🇳🇿",
    "phoneCode": "+64",
    "region": "Oceania",
    "subregion": "Australia and New Zealand",
    "displayOrder": 122,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-nic",
    "name": "Nicaragua",
    "isoAlpha2": "NI",
    "isoAlpha3": "NIC",
    "isoNumeric": "558",
    "officialName": "Republic of Nicaragua",
    "nationality": "Nicaraguan",
    "flag": "🇳🇮",
    "phoneCode": "+505",
    "region": "Americas",
    "subregion": "Central America",
    "displayOrder": 123,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-ner",
    "name": "Niger",
    "isoAlpha2": "NE",
    "isoAlpha3": "NER",
    "isoNumeric": "562",
    "officialName": "Republic of the Niger",
    "nationality": "Nigerien",
    "flag": "🇳🇪",
    "phoneCode": "+227",
    "region": "Africa",
    "subregion": "Western Africa",
    "displayOrder": 124,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-nga",
    "name": "Nigeria",
    "isoAlpha2": "NG",
    "isoAlpha3": "NGA",
    "isoNumeric": "566",
    "officialName": "Federal Republic of Nigeria",
    "nationality": "Nigerian",
    "flag": "🇳🇬",
    "phoneCode": "+234",
    "region": "Africa",
    "subregion": "Western Africa",
    "displayOrder": 125,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-prk",
    "name": "North Korea",
    "isoAlpha2": "KP",
    "isoAlpha3": "PRK",
    "isoNumeric": "408",
    "officialName": "Democratic People's Republic of Korea",
    "nationality": "North Korean",
    "flag": "🇰🇵",
    "phoneCode": "+850",
    "region": "Asia",
    "subregion": "Eastern Asia",
    "displayOrder": 126,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-mkd",
    "name": "North Macedonia",
    "isoAlpha2": "MK",
    "isoAlpha3": "MKD",
    "isoNumeric": "807",
    "officialName": "Republic of North Macedonia",
    "nationality": "Macedonian",
    "flag": "🇲🇰",
    "phoneCode": "+389",
    "region": "Europe",
    "subregion": "Southern Europe",
    "displayOrder": 127,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-nor",
    "name": "Norway",
    "isoAlpha2": "NO",
    "isoAlpha3": "NOR",
    "isoNumeric": "578",
    "officialName": "Kingdom of Norway",
    "nationality": "Norwegian",
    "flag": "🇳🇴",
    "phoneCode": "+47",
    "region": "Europe",
    "subregion": "Northern Europe",
    "displayOrder": 128,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-omn",
    "name": "Oman",
    "isoAlpha2": "OM",
    "isoAlpha3": "OMN",
    "isoNumeric": "512",
    "officialName": "Sultanate of Oman",
    "nationality": "Omani",
    "flag": "🇴🇲",
    "phoneCode": "+968",
    "region": "Asia",
    "subregion": "Western Asia",
    "displayOrder": 129,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-pak",
    "name": "Pakistan",
    "isoAlpha2": "PK",
    "isoAlpha3": "PAK",
    "isoNumeric": "586",
    "officialName": "Islamic Republic of Pakistan",
    "nationality": "Pakistani",
    "flag": "🇵🇰",
    "phoneCode": "+92",
    "region": "Asia",
    "subregion": "Southern Asia",
    "displayOrder": 130,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-plw",
    "name": "Palau",
    "isoAlpha2": "PW",
    "isoAlpha3": "PLW",
    "isoNumeric": "585",
    "officialName": "Republic of Palau",
    "nationality": "Palauan",
    "flag": "🇵🇼",
    "phoneCode": "+680",
    "region": "Oceania",
    "subregion": "Micronesia",
    "displayOrder": 131,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-pse",
    "name": "Palestine",
    "isoAlpha2": "PS",
    "isoAlpha3": "PSE",
    "isoNumeric": "275",
    "officialName": "State of Palestine",
    "nationality": "Palestinian",
    "flag": "🇵🇸",
    "phoneCode": "+970",
    "region": "Asia",
    "subregion": "Western Asia",
    "displayOrder": 132,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-pan",
    "name": "Panama",
    "isoAlpha2": "PA",
    "isoAlpha3": "PAN",
    "isoNumeric": "591",
    "officialName": "Republic of Panama",
    "nationality": "Panamanian",
    "flag": "🇵🇦",
    "phoneCode": "+507",
    "region": "Americas",
    "subregion": "Central America",
    "displayOrder": 133,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-png",
    "name": "Papua New Guinea",
    "isoAlpha2": "PG",
    "isoAlpha3": "PNG",
    "isoNumeric": "598",
    "officialName": "Independent State of Papua New Guinea",
    "nationality": "Papua New Guinean",
    "flag": "🇵🇬",
    "phoneCode": "+675",
    "region": "Oceania",
    "subregion": "Melanesia",
    "displayOrder": 134,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-pry",
    "name": "Paraguay",
    "isoAlpha2": "PY",
    "isoAlpha3": "PRY",
    "isoNumeric": "600",
    "officialName": "Republic of Paraguay",
    "nationality": "Paraguayan",
    "flag": "🇵🇾",
    "phoneCode": "+595",
    "region": "Americas",
    "subregion": "South America",
    "displayOrder": 135,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-per",
    "name": "Peru",
    "isoAlpha2": "PE",
    "isoAlpha3": "PER",
    "isoNumeric": "604",
    "officialName": "Republic of Peru",
    "nationality": "Peruvian",
    "flag": "🇵🇪",
    "phoneCode": "+51",
    "region": "Americas",
    "subregion": "South America",
    "displayOrder": 136,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-phl",
    "name": "Philippines",
    "isoAlpha2": "PH",
    "isoAlpha3": "PHL",
    "isoNumeric": "608",
    "officialName": "Republic of the Philippines",
    "nationality": "Filipino",
    "flag": "🇵🇭",
    "phoneCode": "+63",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "displayOrder": 137,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-pol",
    "name": "Poland",
    "isoAlpha2": "PL",
    "isoAlpha3": "POL",
    "isoNumeric": "616",
    "officialName": "Republic of Poland",
    "nationality": "Polish",
    "flag": "🇵🇱",
    "phoneCode": "+48",
    "region": "Europe",
    "subregion": "Eastern Europe",
    "displayOrder": 138,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-prt",
    "name": "Portugal",
    "isoAlpha2": "PT",
    "isoAlpha3": "PRT",
    "isoNumeric": "620",
    "officialName": "Portuguese Republic",
    "nationality": "Portuguese",
    "flag": "🇵🇹",
    "phoneCode": "+351",
    "region": "Europe",
    "subregion": "Southern Europe",
    "displayOrder": 139,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-qat",
    "name": "Qatar",
    "isoAlpha2": "QA",
    "isoAlpha3": "QAT",
    "isoNumeric": "634",
    "officialName": "State of Qatar",
    "nationality": "Qatari",
    "flag": "🇶🇦",
    "phoneCode": "+974",
    "region": "Asia",
    "subregion": "Western Asia",
    "displayOrder": 140,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-rou",
    "name": "Romania",
    "isoAlpha2": "RO",
    "isoAlpha3": "ROU",
    "isoNumeric": "642",
    "officialName": "Romania",
    "nationality": "Romanian",
    "flag": "🇷🇴",
    "phoneCode": "+40",
    "region": "Europe",
    "subregion": "Eastern Europe",
    "displayOrder": 141,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-rus",
    "name": "Russia",
    "isoAlpha2": "RU",
    "isoAlpha3": "RUS",
    "isoNumeric": "643",
    "officialName": "Russian Federation",
    "nationality": "Russian",
    "flag": "🇷🇺",
    "phoneCode": "+7",
    "region": "Europe",
    "subregion": "Eastern Europe",
    "displayOrder": 142,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-rwa",
    "name": "Rwanda",
    "isoAlpha2": "RW",
    "isoAlpha3": "RWA",
    "isoNumeric": "646",
    "officialName": "Republic of Rwanda",
    "nationality": "Rwandan",
    "flag": "🇷🇼",
    "phoneCode": "+250",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "displayOrder": 143,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-kna",
    "name": "Saint Kitts and Nevis",
    "isoAlpha2": "KN",
    "isoAlpha3": "KNA",
    "isoNumeric": "659",
    "officialName": "Federation of Saint Christopher and Nevis",
    "nationality": "Kittitian, Nevisian",
    "flag": "🇰🇳",
    "phoneCode": "+1-869",
    "region": "Americas",
    "subregion": "Caribbean",
    "displayOrder": 144,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-lca",
    "name": "Saint Lucia",
    "isoAlpha2": "LC",
    "isoAlpha3": "LCA",
    "isoNumeric": "662",
    "officialName": "Saint Lucia",
    "nationality": "Saint Lucian",
    "flag": "🇱🇨",
    "phoneCode": "+1-758",
    "region": "Americas",
    "subregion": "Caribbean",
    "displayOrder": 145,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-vct",
    "name": "Saint Vincent and the Grenadines",
    "isoAlpha2": "VC",
    "isoAlpha3": "VCT",
    "isoNumeric": "670",
    "officialName": "Saint Vincent and the Grenadines",
    "nationality": "Vincentian",
    "flag": "🇻🇨",
    "phoneCode": "+1-784",
    "region": "Americas",
    "subregion": "Caribbean",
    "displayOrder": 146,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-wsm",
    "name": "Samoa",
    "isoAlpha2": "WS",
    "isoAlpha3": "WSM",
    "isoNumeric": "882",
    "officialName": "Independent State of Samoa",
    "nationality": "Samoan",
    "flag": "🇼🇸",
    "phoneCode": "+685",
    "region": "Oceania",
    "subregion": "Polynesia",
    "displayOrder": 147,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-smr",
    "name": "San Marino",
    "isoAlpha2": "SM",
    "isoAlpha3": "SMR",
    "isoNumeric": "674",
    "officialName": "Republic of San Marino",
    "nationality": "Sammarinese",
    "flag": "🇸🇲",
    "phoneCode": "+378",
    "region": "Europe",
    "subregion": "Southern Europe",
    "displayOrder": 148,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-stp",
    "name": "Sao Tome and Principe",
    "isoAlpha2": "ST",
    "isoAlpha3": "STP",
    "isoNumeric": "678",
    "officialName": "Democratic Republic of São Tomé and Príncipe",
    "nationality": "São Toméan",
    "flag": "🇸🇹",
    "phoneCode": "+239",
    "region": "Africa",
    "subregion": "Middle Africa",
    "displayOrder": 149,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-sau",
    "name": "Saudi Arabia",
    "isoAlpha2": "SA",
    "isoAlpha3": "SAU",
    "isoNumeric": "682",
    "officialName": "Kingdom of Saudi Arabia",
    "nationality": "Saudi",
    "flag": "🇸🇦",
    "phoneCode": "+966",
    "region": "Asia",
    "subregion": "Western Asia",
    "displayOrder": 150,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-sen",
    "name": "Senegal",
    "isoAlpha2": "SN",
    "isoAlpha3": "SEN",
    "isoNumeric": "686",
    "officialName": "Republic of Senegal",
    "nationality": "Senegalese",
    "flag": "🇸🇳",
    "phoneCode": "+221",
    "region": "Africa",
    "subregion": "Western Africa",
    "displayOrder": 151,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-srb",
    "name": "Serbia",
    "isoAlpha2": "RS",
    "isoAlpha3": "SRB",
    "isoNumeric": "688",
    "officialName": "Republic of Serbia",
    "nationality": "Serbian",
    "flag": "🇷🇸",
    "phoneCode": "+381",
    "region": "Europe",
    "subregion": "Southern Europe",
    "displayOrder": 152,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-syc",
    "name": "Seychelles",
    "isoAlpha2": "SC",
    "isoAlpha3": "SYC",
    "isoNumeric": "690",
    "officialName": "Republic of Seychelles",
    "nationality": "Seychellois",
    "flag": "🇸🇨",
    "phoneCode": "+248",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "displayOrder": 153,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-sle",
    "name": "Sierra Leone",
    "isoAlpha2": "SL",
    "isoAlpha3": "SLE",
    "isoNumeric": "694",
    "officialName": "Republic of Sierra Leone",
    "nationality": "Sierra Leonean",
    "flag": "🇸🇱",
    "phoneCode": "+232",
    "region": "Africa",
    "subregion": "Western Africa",
    "displayOrder": 154,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-sgp",
    "name": "Singapore",
    "isoAlpha2": "SG",
    "isoAlpha3": "SGP",
    "isoNumeric": "702",
    "officialName": "Republic of Singapore",
    "nationality": "Singaporean",
    "flag": "🇸🇬",
    "phoneCode": "+65",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "displayOrder": 155,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-svk",
    "name": "Slovakia",
    "isoAlpha2": "SK",
    "isoAlpha3": "SVK",
    "isoNumeric": "703",
    "officialName": "Slovak Republic",
    "nationality": "Slovak",
    "flag": "🇸🇰",
    "phoneCode": "+421",
    "region": "Europe",
    "subregion": "Eastern Europe",
    "displayOrder": 156,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-svn",
    "name": "Slovenia",
    "isoAlpha2": "SI",
    "isoAlpha3": "SVN",
    "isoNumeric": "705",
    "officialName": "Republic of Slovenia",
    "nationality": "Slovene, Slovenian",
    "flag": "🇸🇮",
    "phoneCode": "+386",
    "region": "Europe",
    "subregion": "Southern Europe",
    "displayOrder": 157,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-slb",
    "name": "Solomon Islands",
    "isoAlpha2": "SB",
    "isoAlpha3": "SLB",
    "isoNumeric": "090",
    "officialName": "Solomon Islands",
    "nationality": "Solomon Islander",
    "flag": "🇸🇧",
    "phoneCode": "+677",
    "region": "Oceania",
    "subregion": "Melanesia",
    "displayOrder": 158,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-som",
    "name": "Somalia",
    "isoAlpha2": "SO",
    "isoAlpha3": "SOM",
    "isoNumeric": "706",
    "officialName": "Federal Republic of Somalia",
    "nationality": "Somali",
    "flag": "🇸🇴",
    "phoneCode": "+252",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "displayOrder": 159,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-zaf",
    "name": "South Africa",
    "isoAlpha2": "ZA",
    "isoAlpha3": "ZAF",
    "isoNumeric": "710",
    "officialName": "Republic of South Africa",
    "nationality": "South African",
    "flag": "🇿🇦",
    "phoneCode": "+27",
    "region": "Africa",
    "subregion": "Southern Africa",
    "displayOrder": 160,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-kor",
    "name": "South Korea",
    "isoAlpha2": "KR",
    "isoAlpha3": "KOR",
    "isoNumeric": "410",
    "officialName": "Republic of Korea",
    "nationality": "South Korean",
    "flag": "🇰🇷",
    "phoneCode": "+82",
    "region": "Asia",
    "subregion": "Eastern Asia",
    "displayOrder": 161,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-ssd",
    "name": "South Sudan",
    "isoAlpha2": "SS",
    "isoAlpha3": "SSD",
    "isoNumeric": "728",
    "officialName": "Republic of South Sudan",
    "nationality": "South Sudanese",
    "flag": "🇸🇸",
    "phoneCode": "+211",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "displayOrder": 162,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-esp",
    "name": "Spain",
    "isoAlpha2": "ES",
    "isoAlpha3": "ESP",
    "isoNumeric": "724",
    "officialName": "Kingdom of Spain",
    "nationality": "Spanish",
    "flag": "🇪🇸",
    "phoneCode": "+34",
    "region": "Europe",
    "subregion": "Southern Europe",
    "displayOrder": 163,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-lka",
    "name": "Sri Lanka",
    "isoAlpha2": "LK",
    "isoAlpha3": "LKA",
    "isoNumeric": "144",
    "officialName": "Democratic Socialist Republic of Sri Lanka",
    "nationality": "Sri Lankan",
    "flag": "🇱🇰",
    "phoneCode": "+94",
    "region": "Asia",
    "subregion": "Southern Asia",
    "displayOrder": 164,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-sdn",
    "name": "Sudan",
    "isoAlpha2": "SD",
    "isoAlpha3": "SDN",
    "isoNumeric": "729",
    "officialName": "Republic of the Sudan",
    "nationality": "Sudanese",
    "flag": "🇸🇩",
    "phoneCode": "+249",
    "region": "Africa",
    "subregion": "Northern Africa",
    "displayOrder": 165,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-sur",
    "name": "Suriname",
    "isoAlpha2": "SR",
    "isoAlpha3": "SUR",
    "isoNumeric": "740",
    "officialName": "Republic of Suriname",
    "nationality": "Surinamese",
    "flag": "🇸🇷",
    "phoneCode": "+597",
    "region": "Americas",
    "subregion": "South America",
    "displayOrder": 166,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-swe",
    "name": "Sweden",
    "isoAlpha2": "SE",
    "isoAlpha3": "SWE",
    "isoNumeric": "752",
    "officialName": "Kingdom of Sweden",
    "nationality": "Swedish",
    "flag": "🇸🇪",
    "phoneCode": "+46",
    "region": "Europe",
    "subregion": "Northern Europe",
    "displayOrder": 167,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-che",
    "name": "Switzerland",
    "isoAlpha2": "CH",
    "isoAlpha3": "CHE",
    "isoNumeric": "756",
    "officialName": "Swiss Confederation",
    "nationality": "Swiss",
    "flag": "🇨🇭",
    "phoneCode": "+41",
    "region": "Europe",
    "subregion": "Western Europe",
    "displayOrder": 168,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-syr",
    "name": "Syria",
    "isoAlpha2": "SY",
    "isoAlpha3": "SYR",
    "isoNumeric": "760",
    "officialName": "Syrian Arab Republic",
    "nationality": "Syrian",
    "flag": "🇸🇾",
    "phoneCode": "+963",
    "region": "Asia",
    "subregion": "Western Asia",
    "displayOrder": 169,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-twn",
    "name": "Taiwan",
    "isoAlpha2": "TW",
    "isoAlpha3": "TWN",
    "isoNumeric": "158",
    "officialName": "Republic of China (Taiwan)",
    "nationality": "Taiwanese",
    "flag": "🇹🇼",
    "phoneCode": "+886",
    "region": "Asia",
    "subregion": "Eastern Asia",
    "displayOrder": 170,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-tjk",
    "name": "Tajikistan",
    "isoAlpha2": "TJ",
    "isoAlpha3": "TJK",
    "isoNumeric": "762",
    "officialName": "Republic of Tajikistan",
    "nationality": "Tajikistani",
    "flag": "🇹🇯",
    "phoneCode": "+992",
    "region": "Asia",
    "subregion": "Central Asia",
    "displayOrder": 171,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-tza",
    "name": "Tanzania",
    "isoAlpha2": "TZ",
    "isoAlpha3": "TZA",
    "isoNumeric": "834",
    "officialName": "United Republic of Tanzania",
    "nationality": "Tanzanian",
    "flag": "🇹🇿",
    "phoneCode": "+255",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "displayOrder": 172,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-tha",
    "name": "Thailand",
    "isoAlpha2": "TH",
    "isoAlpha3": "THA",
    "isoNumeric": "764",
    "officialName": "Kingdom of Thailand",
    "nationality": "Thai",
    "flag": "🇹🇭",
    "phoneCode": "+66",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "displayOrder": 173,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-tls",
    "name": "Timor-Leste",
    "isoAlpha2": "TL",
    "isoAlpha3": "TLS",
    "isoNumeric": "626",
    "officialName": "Democratic Republic of Timor-Leste",
    "nationality": "Timorese",
    "flag": "🇹🇱",
    "phoneCode": "+670",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "displayOrder": 174,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-tgo",
    "name": "Togo",
    "isoAlpha2": "TG",
    "isoAlpha3": "TGO",
    "isoNumeric": "768",
    "officialName": "Togolese Republic",
    "nationality": "Togolese",
    "flag": "🇹🇬",
    "phoneCode": "+228",
    "region": "Africa",
    "subregion": "Western Africa",
    "displayOrder": 175,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-ton",
    "name": "Tonga",
    "isoAlpha2": "TO",
    "isoAlpha3": "TON",
    "isoNumeric": "776",
    "officialName": "Kingdom of Tonga",
    "nationality": "Tongan",
    "flag": "🇹🇴",
    "phoneCode": "+676",
    "region": "Oceania",
    "subregion": "Polynesia",
    "displayOrder": 176,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-tto",
    "name": "Trinidad and Tobago",
    "isoAlpha2": "TT",
    "isoAlpha3": "TTO",
    "isoNumeric": "780",
    "officialName": "Republic of Trinidad and Tobago",
    "nationality": "Trinidadian, Tobagonian",
    "flag": "🇹🇹",
    "phoneCode": "+1-868",
    "region": "Americas",
    "subregion": "Caribbean",
    "displayOrder": 177,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-tun",
    "name": "Tunisia",
    "isoAlpha2": "TN",
    "isoAlpha3": "TUN",
    "isoNumeric": "788",
    "officialName": "Republic of Tunisia",
    "nationality": "Tunisian",
    "flag": "🇹🇳",
    "phoneCode": "+216",
    "region": "Africa",
    "subregion": "Northern Africa",
    "displayOrder": 178,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-tur",
    "name": "Turkey",
    "isoAlpha2": "TR",
    "isoAlpha3": "TUR",
    "isoNumeric": "792",
    "officialName": "Republic of Türkiye",
    "nationality": "Turkish",
    "flag": "🇹🇷",
    "phoneCode": "+90",
    "region": "Asia",
    "subregion": "Western Asia",
    "displayOrder": 179,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-tkm",
    "name": "Turkmenistan",
    "isoAlpha2": "TM",
    "isoAlpha3": "TKM",
    "isoNumeric": "795",
    "officialName": "Turkmenistan",
    "nationality": "Turkmen",
    "flag": "🇹🇲",
    "phoneCode": "+993",
    "region": "Asia",
    "subregion": "Central Asia",
    "displayOrder": 180,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-tuv",
    "name": "Tuvalu",
    "isoAlpha2": "TV",
    "isoAlpha3": "TUV",
    "isoNumeric": "798",
    "officialName": "Tuvalu",
    "nationality": "Tuvaluan",
    "flag": "🇹🇻",
    "phoneCode": "+688",
    "region": "Oceania",
    "subregion": "Polynesia",
    "displayOrder": 181,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-uga",
    "name": "Uganda",
    "isoAlpha2": "UG",
    "isoAlpha3": "UGA",
    "isoNumeric": "800",
    "officialName": "Republic of Uganda",
    "nationality": "Ugandan",
    "flag": "🇺🇬",
    "phoneCode": "+256",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "displayOrder": 182,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-ukr",
    "name": "Ukraine",
    "isoAlpha2": "UA",
    "isoAlpha3": "UKR",
    "isoNumeric": "804",
    "officialName": "Ukraine",
    "nationality": "Ukrainian",
    "flag": "🇺🇦",
    "phoneCode": "+380",
    "region": "Europe",
    "subregion": "Eastern Europe",
    "displayOrder": 183,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-are",
    "name": "United Arab Emirates",
    "isoAlpha2": "AE",
    "isoAlpha3": "ARE",
    "isoNumeric": "784",
    "officialName": "United Arab Emirates",
    "nationality": "Emirati",
    "flag": "🇦🇪",
    "phoneCode": "+971",
    "region": "Asia",
    "subregion": "Western Asia",
    "displayOrder": 184,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-gbr",
    "name": "United Kingdom",
    "isoAlpha2": "GB",
    "isoAlpha3": "GBR",
    "isoNumeric": "826",
    "officialName": "United Kingdom of Great Britain and Northern Ireland",
    "nationality": "British",
    "flag": "🇬🇧",
    "phoneCode": "+44",
    "region": "Europe",
    "subregion": "Northern Europe",
    "displayOrder": 185,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-usa",
    "name": "United States",
    "isoAlpha2": "US",
    "isoAlpha3": "USA",
    "isoNumeric": "840",
    "officialName": "United States of America",
    "nationality": "American",
    "flag": "🇺🇸",
    "phoneCode": "+1",
    "region": "Americas",
    "subregion": "Northern America",
    "displayOrder": 186,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-ury",
    "name": "Uruguay",
    "isoAlpha2": "UY",
    "isoAlpha3": "URY",
    "isoNumeric": "858",
    "officialName": "Oriental Republic of Uruguay",
    "nationality": "Uruguayan",
    "flag": "🇺🇾",
    "phoneCode": "+598",
    "region": "Americas",
    "subregion": "South America",
    "displayOrder": 187,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-uzb",
    "name": "Uzbekistan",
    "isoAlpha2": "UZ",
    "isoAlpha3": "UZB",
    "isoNumeric": "860",
    "officialName": "Republic of Uzbekistan",
    "nationality": "Uzbekistani",
    "flag": "🇺🇿",
    "phoneCode": "+998",
    "region": "Asia",
    "subregion": "Central Asia",
    "displayOrder": 188,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-vut",
    "name": "Vanuatu",
    "isoAlpha2": "VU",
    "isoAlpha3": "VUT",
    "isoNumeric": "548",
    "officialName": "Republic of Vanuatu",
    "nationality": "Ni-Vanuatu",
    "flag": "🇻🇺",
    "phoneCode": "+678",
    "region": "Oceania",
    "subregion": "Melanesia",
    "displayOrder": 189,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-vat",
    "name": "Vatican City",
    "isoAlpha2": "VA",
    "isoAlpha3": "VAT",
    "isoNumeric": "336",
    "officialName": "Vatican City State",
    "nationality": "Vatican",
    "flag": "🇻🇦",
    "phoneCode": "+379",
    "region": "Europe",
    "subregion": "Southern Europe",
    "displayOrder": 190,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-ven",
    "name": "Venezuela",
    "isoAlpha2": "VE",
    "isoAlpha3": "VEN",
    "isoNumeric": "862",
    "officialName": "Bolivarian Republic of Venezuela",
    "nationality": "Venezuelan",
    "flag": "🇻🇪",
    "phoneCode": "+58",
    "region": "Americas",
    "subregion": "South America",
    "displayOrder": 191,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-vnm",
    "name": "Vietnam",
    "isoAlpha2": "VN",
    "isoAlpha3": "VNM",
    "isoNumeric": "704",
    "officialName": "Socialist Republic of Vietnam",
    "nationality": "Vietnamese",
    "flag": "🇻🇳",
    "phoneCode": "+84",
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "displayOrder": 192,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-yem",
    "name": "Yemen",
    "isoAlpha2": "YE",
    "isoAlpha3": "YEM",
    "isoNumeric": "887",
    "officialName": "Republic of Yemen",
    "nationality": "Yemeni",
    "flag": "🇾🇪",
    "phoneCode": "+967",
    "region": "Asia",
    "subregion": "Western Asia",
    "displayOrder": 193,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-zmb",
    "name": "Zambia",
    "isoAlpha2": "ZM",
    "isoAlpha3": "ZMB",
    "isoNumeric": "894",
    "officialName": "Republic of Zambia",
    "nationality": "Zambian",
    "flag": "🇿🇲",
    "phoneCode": "+260",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "displayOrder": 194,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  },
  {
    "id": "c-zwe",
    "name": "Zimbabwe",
    "isoAlpha2": "ZW",
    "isoAlpha3": "ZWE",
    "isoNumeric": "716",
    "officialName": "Republic of Zimbabwe",
    "nationality": "Zimbabwean",
    "flag": "🇿🇼",
    "phoneCode": "+263",
    "region": "Africa",
    "subregion": "Eastern Africa",
    "displayOrder": 195,
    "isActive": true,
    "createdAt": "2026-01-01T00:00:00Z",
    "updatedAt": "2026-01-01T00:00:00Z"
  }
];
